---
name: RELEASE

on:
  push:
    tags:
      - '*'

jobs:
  galaxy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip virtualenv
          make install
      - name: Import role on galaxy
        run: ansible-galaxy role import --token ${{ secrets.GALAXY_API_KEY }} ${GITHUB_REPOSITORY/\// }
